// Generated by CoffeeScript 1.8.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __slice = [].slice;

(function($, window) {
  var MrUploader;
  MrUploader = (function() {
    MrUploader.prototype.defaults = {
      multiple: true,
      cropping: false,
      uploadUrl: '/upload.php',
      crop: {
        boxWidth: 800,
        aspectRatio: 3 / 2,
        keySupport: false,
        allowSelect: false,
        minSize: [300, 200],
        setSelect: [0, 0, 600, 400]
      }
    };

    function MrUploader(el, options) {
      this.hideFullscreen = __bind(this.hideFullscreen, this);
      this.showFullscreen = __bind(this.showFullscreen, this);
      this.onCloseClick = __bind(this.onCloseClick, this);
      this.updateElementText = __bind(this.updateElementText, this);
      this.getStagedFileMeta = __bind(this.getStagedFileMeta, this);
      this.changePreview = __bind(this.changePreview, this);
      this.onReaderLoad = __bind(this.onReaderLoad, this);
      this.onUploaderFileChanged = __bind(this.onUploaderFileChanged, this);
      this.onUploadClick = __bind(this.onUploadClick, this);
      this.setStaged = __bind(this.setStaged, this);
      this.onCroppingSelected = __bind(this.onCroppingSelected, this);
      this.onElementClick = __bind(this.onElementClick, this);
      this.$el = $(el);
      this.$options = $.extend({}, this.defaults, options);
      this.addContent();
      this.$el.click(this.onElementClick);
      this.setStaged(null);
    }

    MrUploader.prototype.onElementClick = function() {
      return this.showFullscreen();
    };

    MrUploader.prototype.addContent = function() {
      var close, crop, header, title, upload;
      this.$container = $('<div/>').hide().addClass('mr-uploader-fullscreen-mode').css('text-align', 'center');
      header = $('<div/>');
      close = $('<h1><a href="#" class="mr-uploader-fullscreen-close">&times</a></h1>');
      close.click(this.onCloseClick);
      title = $('<h2/>').text('Choose & Crop');
      header.append(close);
      header.append(title);
      this.$container.append(header);
      crop = $('<div />');
      this.$input = $('<input type="file" accept="image/*" />').css('padding-bottom', '10px');
      this.$input.change(this.onUploaderFileChanged);
      crop.append(this.$input);
      this.$photos = $('<div id="mr-uploader-images">&nbsp;</div>');
      crop.append(this.$photos);
      upload = $('<button>Upload</button>');
      upload.click(this.onUploadClick);
      crop.append(upload);
      this.$container.append(crop);
      this.$container.append('<hr />');
      this.$previews = $('<div />');
      this.$container.append(this.$previews);
      return $('body').append(this.$container);
    };

    MrUploader.prototype.onCroppingSelected = function(crop, image, meta) {
      crop = {
        x: Math.round(crop.x),
        y: Math.round(crop.y),
        x2: Math.round(crop.x2),
        y2: Math.round(crop.y2),
        width: Math.round(crop.w),
        height: Math.round(crop.h)
      };
      meta.width = image.width();
      meta.height = image.height();
      return this.setStaged({
        $image: image,
        meta: meta,
        crop: crop
      });
    };

    MrUploader.prototype.setStaged = function(staged) {
      this.staged = staged;
    };

    MrUploader.prototype.onUploadClick = function() {
      var meta, photo, request, url;
      if (this.staged == null) {
        return alert('Please choose a photo to upload');
      }
      url = this.$options.uploadUrl;
      photo = this.staged.image.attr('src');
      meta = this.staged.meta;
      request = $.ajax({
        type: 'POST',
        url: url,
        data: {
          photo: photo,
          meta: meta
        },
        cache: false
      });
      request.done(function(response, status, xhr) {
        return console.log(response);
      });
      return request.fail(function(xhr, status, error) {
        return console.error(error);
      });
    };

    MrUploader.prototype.onUploaderFileChanged = function(e) {
      var file, input, reader, _i, _len, _ref, _results;
      input = this.$input[0];
      if ((input.files != null) && input.files.length > 0) {
        reader = new FileReader();
        reader.onload = this.onReaderLoad;
        _ref = input.files;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          file = _ref[_i];
          _results.push(reader.readAsDataURL(file));
        }
        return _results;
      }
    };

    MrUploader.prototype.onReaderLoad = function(e) {
      var crop, img, meta, preview, previewImage;
      img = $('<img src="' + e.target.result + '" />');
      crop = this.$options.crop;
      meta = this.getStagedFileMeta();
      preview = $('<div class="mr-uploader-preview"/>');
      previewImage = $('<img />').attr('src', e.target.result);
      preview.html(previewImage);
      this.$previews.prepend(preview);
      crop.onSelect = (function(_this) {
        return function(crop) {
          return _this.onCroppingSelected(crop, img, meta);
        };
      })(this);
      crop.onChange = (function(_this) {
        return function(crop) {
          return _this.changePreview(crop, previewImage);
        };
      })(this);
      this.$photos.html(img);
      img.Jcrop(crop);
      return this.updateElementText();
    };

    MrUploader.prototype.changePreview = function(crop, $thumbnail) {
      var rx, ry;
      if (this.staged != null) {
        rx = 300 / crop.w;
        ry = 200 / crop.h;
        return $thumbnail.css({
          marginTop: '-' + Math.round(ry * crop.y) + 'px',
          marginLeft: '-' + Math.round(rx * crop.x) + 'px',
          width: Math.round(rx * this.staged.meta.width) + 'px',
          height: Math.round(ry * this.staged.meta.height) + 'px'
        });
      }
    };

    MrUploader.prototype.getStagedFileMeta = function() {
      var file, input;
      input = this.$input[0];
      file = input.files[0];
      return {
        name: file.name,
        size: file.size,
        type: file.type
      };
    };

    MrUploader.prototype.updateElementText = function() {
      return this.$el.text();
    };

    MrUploader.prototype.onCloseClick = function() {
      return this.hideFullscreen();
    };

    MrUploader.prototype.showFullscreen = function() {
      return this.$container.fadeIn();
    };

    MrUploader.prototype.hideFullscreen = function() {
      return this.$container.fadeOut();
    };

    return MrUploader;

  })();
  return $.fn.extend({
    mrUploader: function() {
      var $this, args, data, option, upload;
      option = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      $this = this.first();
      data = $this.data('mrUploader');
      if (!data) {
        upload = new MrUploader(this, option);
        $this.data('mrUploader', (data = upload));
        return upload;
      }
      if (typeof option === 'string') {
        return data[optiokn].apply(data, args);
      }
    }
  });
})(window.jQuery, window);
